# Generated by Django 4.2.13 on 2024-09-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Дополнительные Фотографии'),
        ),
    ]
